version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  apt_packages:
    - pandoc
  jobs:
    post_create_environment:
      - pip install torch==2.0.0+cpu --extra-index-url https://download.pytorch.org/whl/cpu
      - pip install cell-decipher
      - pip --no-cache-dir install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
sphinx:
  configuration: docs/conf.py
python:
  install:
    - requirements: docs/requirements.txt
