cluster: "sbatch -J {cluster.jobname} -A {cluster.account} -p {cluster.partition} -N {cluster.n_node} -n {cluster.n_task} -c {cluster.n_cpu} {cluster.gres} -o {cluster.output} -e {cluster.error}"
cluster-config: profiles/hpc/hpc.yaml
printshellcmds: true
reason: true
keep-going: true
resources: gpu=64
use-conda: true
# use-singularity: true
# singularity-args: " --nv"
rerun-incomplete: true
