#-------------------------------- Global ----------------------------------#
timeout: 1d
seed: 8

#-------------------------------- Dataset ----------------------------------#
# name as: <species>_<organ>_<tech>_<disease>_<other>_s<slice_index>
dataset:

  human_pbmc_10x_mimic:
    data: 'input/mimic/merged.h5ad'
    cell_type: 'cell_type'
    region: 'region'

  human_breastcancer_xenium:
    data: 'input/xenium/Xenium_breast_anno_region.h5ad'
    cell_type: 'cell_type'
    region: 'region'

  human_brainaging_merfish:
    data: 'input/merfish/brain_aging.h5ad'
    cell_type: 'cell_type'
    region: 'tissue'

#--------------------------- Benchmark Methods -----------------------------#
method:
  - spider
  # # spatial
  - banksy
  - stagate
  - slat
  # # non-spatial
  - harmony
  - scvi
  - scanpy


#-------------------------- Hyper-parameter search -------------------------#
hyperparam_conf:
  human_pbmc_10x_mimic:
    dropout_gex:
      default: 0.6
      choices: [0.5, 0.55, 0.6, 0.65]
    k:
      default: 25
      choices: [25]
    center_emb_dim:
      default: 32
      choices: [32]
    nbr_emb_dim:
      default: 32
      choices: [32]
    epochs:
      default: 8
      choices: [8]
    dropout:
      default: 0.0
      choices: [0.0]
    transformer_layers:
      default: 2
      choices: [2, 3]
    temperature_center:
      default: 0.1
      choices: [0.1, 0.15, 0.2]
    temperature_nbr:
      default: 0.01
      choices: [0.01]
    batch_size:
      default: 128
      choices: [128]

  human_brainaging_merfish:
    dropout_gex:
      default: 0.3
      choices: [0.3, 0.35, 0.4]
    k:
      default: 30
      choices: [20, 30, 40]
    center_emb_dim:
      default: 32
      choices: [32]
    nbr_emb_dim:
      default: 32
      choices: [32]
    epochs:
      default: 2
      choices: [2, 4]
    dropout:
      default: 0.0
      choices: [0.0, 0.4]
    transformer_layers:
      default: 2
      choices: [1, 3]
    temperature_center:
      default: 0.05
      choices: [0.03, 0.05, 0.07]
    temperature_nbr:
      default: 0.05
      choices: [0.05, 0.07, 0.1,]
    batch_size:
      default: 64
      choices: [64, 256]

  human_breastcancer_xenium:
    dropout_gex:
      default: 0.3
      choices: [0.3]
    k:
      default: 20
      choices: [20, 25, 30]
    center_emb_dim:
      default: 32
      choices: [32]
    nbr_emb_dim:
      default: 32
      choices: [32]
    epochs:
      default: 6
      choices: [6]
    dropout:
      default: 0.2
      choices: [0.2]
    transformer_layers:
      default: 3
      choices: [2]
    temperature_center:
      default: 0.05
      choices: [0.03, 0.05, 0.07]
    temperature_nbr:
      default: 0.05
      choices: [0.03, 0.05, 0.07]
    batch_size:
      default: 64
      choices: [64]
